"use client";

interface Source {
  topic: string;
  problem: string;
}

interface SolutionSectionProps {
  visible: boolean;
  loading: boolean;
  error: string | null;
  answer: string | null;
  processingTime: string | null;
  sources: Source[];
  onScrollToInput: () => void;
  onShowToast: (message: string, type: "success" | "error" | "info") => void;
}

export function SolutionSection({
  visible,
  loading,
  error,
  answer,
  processingTime,
  sources,
  onScrollToInput,
  onShowToast,
}: SolutionSectionProps) {
  const copySolution = () => {
    if (answer) {
      navigator.clipboard
        .writeText(answer)
        .then(() => {
          onShowToast("Solution copied to clipboard!", "success");
        })
        .catch(() => {
          onShowToast("Failed to copy solution", "error");
        });
    }
  };

  const shareAnswer = () => {
    if (typeof navigator !== "undefined" && navigator.share) {
      navigator.share({
        title: "Rehnuma Solution",
        text: answer ? answer.substring(0, 200) + "..." : "",
        url: window.location.href,
      });
    } else {
      navigator.clipboard.writeText(window.location.href);
      onShowToast("Link copied to clipboard!", "success");
    }
  };

  if (!visible) return null;

  return (
    <section
      id="solution-section"
      className="bg-[var(--bg-primary)] h-screen flex flex-col pt-20 pb-4 animate-fade-in"
    >
      <div className="container max-w-[1200px] mx-auto px-6 flex-1 flex flex-col overflow-hidden">
        <div className="max-w-[1000px] mx-auto w-full flex-1 flex flex-col overflow-hidden">
          {/* Section Header */}
          <div className="text-center mb-4 shrink-0">
            <h3
              className="text-[1.75rem] font-semibold mb-1 text-[var(--text-primary)]"
              style={{ fontFamily: "'Space Grotesk', sans-serif" }}
            >
              Solution <span className="text-[1.25rem]">✨</span>
            </h3>
            <p className="text-[var(--text-secondary)] m-0 text-sm">
              Step-by-step explanation generated by AI
            </p>
          </div>

          <div
            className="bg-[var(--bg-secondary)] rounded-2xl border border-[var(--border-custom)] p-6 mb-4 flex-1 overflow-hidden flex flex-col"
            style={{
              boxShadow: "var(--shadow-sm)",
              maxHeight: "calc(100vh - 280px)",
            }}
          >
            {/* Loading State */}
            {loading && (
              <div className="text-center py-16 flex-1 flex flex-col items-center justify-center">
                <div className="w-12 h-12 border-[3px] border-[var(--border-custom)] border-t-[var(--rehnuma-primary)] rounded-full mx-auto mb-6 animate-spin-slow" />
                <p className="text-[var(--text-secondary)] m-0 text-base">
                  <i className="fas fa-brain mr-2"></i>
                  Analyzing your question and retrieving relevant information...
                </p>
              </div>
            )}

            {/* Solution Content - scrollable */}
            {!loading && !error && answer && (
              <div className="py-2 overflow-y-auto flex-1">
                <div className="flex items-center gap-4 mb-6 pb-4 border-b-2 border-[var(--border-custom)]">
                  <div
                    className="w-10 h-10 rounded-xl flex items-center justify-center text-white text-xl shrink-0"
                    style={{
                      background:
                        "linear-gradient(135deg, var(--rehnuma-primary) 0%, var(--rehnuma-primary-light) 100%)",
                    }}
                  >
                    <i className="fas fa-lightbulb"></i>
                  </div>
                  <div>
                    <h4
                      className="m-0 mb-1 text-[1.1rem]"
                      style={{ fontFamily: "'Space Grotesk', sans-serif" }}
                    >
                      Detailed Explanation
                    </h4>
                    <p className="text-[var(--text-secondary)] m-0 text-[0.85rem]">
                      Processing time: {processingTime || "--"}
                    </p>
                  </div>
                </div>

                <div
                  className="text-[1rem] leading-[1.8] whitespace-pre-wrap text-[var(--text-primary)] font-sans"
                  style={{
                    wordBreak: "break-word",
                    overflowWrap: "break-word",
                  }}
                >
                  {answer}
                </div>

                {/* Sources Section */}
                {sources.length > 0 && (
                  <div className="mt-6 pt-6 border-t border-[var(--border-custom)]">
                    <h4 className="text-[1rem] mb-3 font-semibold text-[var(--text-primary)]">
                      <i className="fas fa-book mr-2 text-[var(--rehnuma-primary)]"></i>
                      Reference Materials
                    </h4>
                    <div>
                      {sources.map((source, index) => (
                        <div
                          key={index}
                          className="bg-[var(--bg-primary)] p-3 rounded-lg mt-2"
                          style={{
                            borderLeft: "3px solid var(--rehnuma-primary)",
                          }}
                        >
                          <div className="font-semibold mb-1 text-[var(--text-primary)] text-sm">
                            {source.topic}
                          </div>
                          <div className="text-[0.85rem] text-[var(--text-secondary)]">
                            {source.problem}
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Error State */}
            {!loading && error && (
              <div className="text-center py-16 flex-1 flex flex-col items-center justify-center">
                <div
                  className="w-14 h-14 rounded-full flex items-center justify-center mx-auto mb-4"
                  style={{ background: "#fee2e2" }}
                >
                  <i className="fas fa-exclamation-triangle text-[1.75rem] text-[#dc2626]"></i>
                </div>
                <h4 className="m-0 mb-2 text-[var(--text-primary)]">
                  Error Generating Solution
                </h4>
                <p className="text-[var(--text-secondary)] m-0">{error}</p>
              </div>
            )}
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 items-center justify-center flex-wrap shrink-0">
            <button
              onClick={onScrollToInput}
              className="inline-flex items-center justify-center gap-2 py-2.5 px-5 font-medium text-[var(--text-primary)] bg-[var(--bg-secondary)] border border-[var(--border-custom)] rounded-xl cursor-pointer transition-all duration-200 hover:bg-[var(--bg-tertiary)] hover:-translate-y-0.5 text-sm"
              style={{ boxShadow: "var(--shadow-sm)" }}
            >
              <i className="fas fa-arrow-up"></i>
              Ask Another Question
            </button>
            <button
              onClick={copySolution}
              className="inline-flex items-center justify-center gap-2 py-2.5 px-5 font-medium text-[var(--text-primary)] bg-[var(--bg-secondary)] border border-[var(--border-custom)] rounded-xl cursor-pointer transition-all duration-200 hover:bg-[var(--bg-tertiary)] hover:-translate-y-0.5 text-sm"
              style={{ boxShadow: "var(--shadow-sm)" }}
            >
              <i className="fas fa-copy"></i>
              Copy Solution
            </button>
            <button
              onClick={shareAnswer}
              className="inline-flex items-center justify-center gap-2 py-2.5 px-5 font-medium text-[var(--text-primary)] bg-[var(--bg-secondary)] border border-[var(--border-custom)] rounded-xl cursor-pointer transition-all duration-200 hover:bg-[var(--bg-tertiary)] hover:-translate-y-0.5 text-sm"
              style={{ boxShadow: "var(--shadow-sm)" }}
            >
              <i className="fas fa-share"></i>
              Share
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}
